tasks:
  - name: psql
    env:
      PGPASSWORD: kong
    command: |
      gp await-port 5432
      sleep 60
      docker exec -e PGPASSWORD=kong -it postgres psql -d kong
  - name: ysql
    env:
      PGPASSWORD: kong
    command: |
      gp await-port 5433
      sleep 60
      docker exec -e PGPASSWORD=yugabyte -it yugabytedb /home/yugabyte/tserver/bin/ysqlsh -h 0.0.0.0 -d kong
  - name: kong-gateway
    init: |
      docker-compose -f kong-gateway.yml pull
    command: |
      docker-compose -f kong-gateway.yml up
