tasks:
  # - name: psql
  #   env:
  #     PGPASSWORD: kong
  #   command: |
  #     gp ports await 5432
  #     sleep 10
  #     docker exec -e PGPASSWORD=${PGPASSWORD} -it postgres psql -U kong -d kong
  - name: ysql
    env:
      PGPASSWORD: kong
    command: |
      gp ports await 5433
      sleep 20
      docker exec -e PGPASSWORD=kong -it yugabytedb /home/yugabyte/tserver/bin/ysqlsh -h 0.0.0.0 -U kong -d kong
  - name: kong-gateway
    env:
      YBDB_VERSION: 2.19.2.0-b121
      KONG_VERSION: 3.3.0.0
      PG_VERSION: 14
      DEBUG: "--vv"
    init: |
      docker compose --env-file .envc -f kong-gateway.yml pull
    command: |
      docker compose --env-file .envc -f kong-gateway.yml up

vscode:
  extensions:
    - ms-azuretools.vscode-docker