tasks:
  - name: ysql
    command: |
      gp await-port 5433
      ysqlsh -d alfresco
  - name: alfresco
    init: |
      docker-compose -f alfresco.yml pull
    command: |
      docker-compose -f alfresco.yml up
