image: gitpod/workspace-yugabytedb-preview

tasks:
  - name: ysql
    env:
      YSQL_PASSWORD: alfresco
      YSQL_USER: alfresco
      YSQL_DB: alfresco
    before: |
      yugabyted start --base_dir=$STORE/ybd1 --advertise_address=$HOST
    command: |
      gp await-port 5433
      ysqlsh -d alfresco
  - name: alfresco
    init: |
      docker-compose -f alfresco.yml pull
    command: |
      docker-compose -f alfresco.yml up
