tasks:
  - name: ysql
    env:
      PGPASSWORD: yugabyte
    command: |
      gp await-port 5433
      docker exec -it yugabytedb /home/yugabyte/tserver/bin/ysqlsh -d alfresco
  - name: alfresco
    init: |
      docker-compose -f alfresco.yml pull
    command: |
      docker-compose -f alfresco.yml up
