version: '3'
services:
  alfresco:
    image: docker.io/alfresco/alfresco-content-repository-community
    mem_limit: 1900m
    environment:
      JAVA_TOOL_OPTIONS: >-
        -Dencryption.keystore.type=JCEKS
        -Dencryption.cipherAlgorithm=DESede/CBC/PKCS5Padding
        -Dencryption.keyAlgorithm=DESede
        -Dencryption.keystore.location=/usr/local/tomcat/shared/classes/alfresco/extension/keystore/keystore
        -Dmetadata-keystore.password=mp6yc0UD9e
        -Dmetadata-keystore.aliases=metadata
        -Dmetadata-keystore.metadata.password=oKIWzVdEdA
        -Dmetadata-keystore.metadata.algorithm=DESede
      JAVA_OPTS: >-
        -Ddb.driver=org.postgresql.Driver -Ddb.username=alfresco
        -Ddb.password=alfresco -Ddb.url=jdbc:postgresql://127.0.0.1:5433/alfresco
        -Dshare.host=127.0.0.1 -Dshare.port=8080 -Dalfresco.host=localhost
        -Dalfresco.port=8080 -Dcsrf.filter.enabled=false -Dmessaging.subsystem.autoStart=false
        -XX:MinRAMPercentage=50 -XX:MaxRAMPercentage=80
    depends_on:
    - yugabytedb
  share:
    image: docker.io/alfresco/alfresco-share:7.4.0-M2
    mem_limit: 1g
    environment:
      REPO_HOST: "alfresco"
      REPO_PORT: "8080"
      JAVA_OPTS: >-
        -XX:MinRAMPercentage=50 -XX:MaxRAMPercentage=80
        -Dalfresco.host=localhost -Dalfresco.port=8080
        -Dalfresco.context=alfresco -Dalfresco.protocol=http
  content-app:
    image: alfresco/alfresco-content-app:3.1.0
    mem_limit: 128m
    environment:
      APP_BASE_SHARE_URL: "http://localhost:8080/aca/#/preview/s"
  proxy:
    image: alfresco/alfresco-acs-nginx:3.4.2
    mem_limit: 128m
    environment:
      DISABLE_PROMETHEUS: "true"
      DISABLE_SYNCSERVICE: "true"
      DISABLE_ADW: "true"
      DISABLE_CONTROL_CENTER: "true"
      ENABLE_CONTENT_APP: "true"
    depends_on:
      - alfresco
      - content-app
    ports:
      - "8080:8080"
    links:
      - content-app
      - alfresco
      - share
